apiVersion: v1
kind: Service
metadata:
  name: headless-postgres-service
  namespace: zabbix-namespace
  labels:
    app: postgres
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: database
  clusterIP: None
  selector:
    app: postgres