apiVersion: v1
kind: Service
metadata:
  name: zabbix-frontend-service
  namespace: zabbix-namespace
spec:
  selector:
    app:  zabbix-frontend
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 8080
  type: NodePort