apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: zabbix-namespace
spec:
  selector:
    app:  grafana
  ports:
    - protocol: TCP
      port: 3000  
      targetPort: 3000
  type: NodePort