apiVersion: v1
kind: Service
metadata:
  name: headless-zabbix-ha-service
  namespace: ${NAMESPACE}
  labels:
    app: zabbix-server-ha
spec:
  ports:
    - protocol: TCP
      port: 10051
      targetPort: 10051
      name: server
  clusterIP: None
  selector:
    app: zabbix-server