kind: Cluster 
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-cluster-zabbix
nodes: 
- role: control-plane
- role: worker
  extraMounts: 
  - hostPath: ${CLUSTER_STORAGE}
    containerPath: /files
- role: worker