kind: Cluster 
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-cluster-zabbix
nodes: 
- role: control-plane
- role: worker
  extraMounts: 
  - hostPath: /home/luangomes/Documentos/vs-code/devops-kubernetes-playground/cluster/storage
    containerPath: /files
- role: worker