apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-frontend-deployment
  namespace: ${NAMESPACE}
  labels:
    app: zabbix-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-frontend
  template:
    metadata:
      labels:
        app: zabbix-frontend
    spec:
      containers: 
        - name: zabbix-frontend-container
          image: zabbix/zabbix-web-nginx-pgsql:7.2.6-alpine
          env: 
           - name: DB_SERVER_HOST
             value: headless-postgres-service
           - name: POSTGRES_PASSWORD
             valueFrom: 
              secretKeyRef: 
                name: postgres-credentials
                key: password
           - name: ZBX_SERVER_HOST
             value: headless-zabbix-ha-service ##.${NAMESPACE}.svc.cluster.local
           - name: POSTGRES_USER
             valueFrom:
              secretKeyRef:
                name: zabbix-credentials
                key: user