apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server-deployment
  namespace: zabbix-namespace
  labels:
    app: zabbix-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server-container
        image: zabbix/zabbix-server-pgsql:alpine-trunk 
        env: 
          - name: DB_SERVER_HOST
            value: headless-postgres-service
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: zabbix-credentials
                key: password
          - name: POSTGRES_USER
            valueFrom: 
              secretKeyRef:
                name: zabbix-credentials
                key: user