apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
